FROM --platform=linux/arm64 node:18

ENV NODE_ENV=development

# Set the working directory inside the container to /app
WORKDIR /frontend

# Copy package.json and package-lock.json (if available) into the container
COPY package.json ./

# Install dependencies, including development ones
RUN npm install

# Copy the rest of the source code into the container
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]