openapi: 3.0.0
info:
  title: "{siteName} API"
  version: 1.0.0
  description: >
    API for email validation services

    This API provides email validation capabilities, including single email validation
    and bulk email validation. It uses JWT for authentication, which can be obtained
    using an API key.

    The API supports two main operations:
    1. Validating a single email address
    2. Validating multiple email addresses in bulk

    For bulk validation, you can either send a JSON array of emails or upload a file
    (CSV, XLSX, XLS, or TXT). The results of bulk validation will be sent as a detailed
    CSV report to your registered email address.

servers:
  - url: {apiBaseUrl}

paths:
  /generate_jwt:
    post:
      summary: Generate a JWT bearer token from your API key
      tags:
        - default
      security:
        - APIKeyAuth: []
      description: Generate a JWT token for API authentication
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Generated JWT token
        '401':
          description: Unauthorized. Authentication failed.

  /validate_email:
    post:
      summary: Validate a single email address
      tags:
        - email
      security:
        - BearerAuth: []
      description: Validate a single email address and return its validation status.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address to validate
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_valid:
                    type: boolean
                  reason:
                    type: string

  /validate_emails:
    post:
      summary: Validate multiple emails
      tags:
        - email
      security:
        - BearerAuth: []
      description: >
        Validate multiple email addresses in bulk. A detailed CSV report containing 
        the validation results for each email will be sent to your registered email address.
        You can either send a JSON array of emails or upload a file.
      requestBody:
        content:
          application/json (switch me):
            schema:
              type: object
              properties:
                Emails:
                  type: array
                  items:
                    type: string
                  description: Array of email addresses to validate
            example:
              Emails:
                - "user1@example.com"
                - "user2@example.com"
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: CSV, XLSX, XLS, or TXT file containing email addresses
                columnsToScan:
                  type: string
                  description: Comma-separated list of column names to scan for emails (optional)
      responses:
        '204':
          description: No Content. Validation process started successfully.
        '400':
          description: Bad Request. Invalid input or no emails to validate.
        '401':
          description: Unauthorized. Authentication failed.
        '429':
          description: Too Many Requests. Rate limit exceeded.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - BearerAuth: []  # Apply bearer token auth globally

tags:
  - name: default
    description: General operations
  - name: email
    description: Email validation operations