FROM golang:1.18-alpine

ENV env=dev

WORKDIR /go/src/email-validator

COPY . .

RUN go mod download && go install github.com/cosmtrek/air@latest

WORKDIR /go/src/email-validator/cmd

CMD ["air", "."]