FROM golang:1.22-alpine

ENV env=dev

WORKDIR /go/src/email-validator/api

COPY . .

RUN go install ./...
RUN go install github.com/cosmtrek/air@latest

WORKDIR /go/src/email-validator/api/cmd

CMD ["air", "."]